# Default values for CDB app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# We have only done front for now
name: cdb

front:
  enabled: true
  image:
    repository: registry.gitlab.com/takima-school/images/cdb/www
    tag: latest
  replicaCount: 1
  ingress:
    tlsEnabled: true
    host: front-staging.phappy.takima.school

api:
  enabled: true
  image:
    repository: registry.gitlab.com/takima-school/images/cdb/api
    tag: latest
  replicaCount: 1
  ingress:
    tlsEnabled: true
    host: cdb-api-staging.phappy.takima.school

pg:
  enabled: true
  operator:
    enableLogicalBackup: true
    numberOfInstances: 2
    volumeSize: 1Gi
  replicaCount: 3