{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include ("MyAppCtx.fullname") . }}-api-service
spec:
  selector:
    app: {{ include ("MyAppCtx.fullname") . }}-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
{{- end }}