{{- if .Values.api.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include ("MyAppCtx.fullname") . }}-api
data:
  db_endpoint: {{ include ("MyAppCtx.fullname") . }}-pg:5432
  db_name: "cdb"
{{- end }}