{{- if .Values.api.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: {{ include ("MyAppCtx.fullname") . }}-api-ingress
spec:
  rules:
  - host: {{ .Values.api.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ include ("MyAppCtx.fullname") . }}-api-service
            port:
              number: 8080
        path: /
        pathType: Prefix
  {{- if .Values.api.ingress.tlsEnabled }}
  tls:
  - hosts:
      - {{ .Values.api.ingress.host }}
    secretName: app-wildcard
  {{- end }}
{{- end }}