{{- if .Values.api.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-api
  labels:
    app: {{ .Values.name }}-api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}-api
  template:
    metadata:
      labels:
        app: {{ .Values.name }}-api
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
      containers:
      - name: {{ .Values.name }}-api
        image: {{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}
        env:
        - name: DB_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.name }}-api
              key: db_endpoint
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.name }}-api
              key: db_name
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.name }}.{{ .Values.name }}-pg.credentials.postgresql.acid.zalan.do
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.name }}.{{ .Values.name }}-pg.credentials.postgresql.acid.zalan.do
              key: password
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "712Mi"
            cpu: "0.5"
          limits:
            memory: "2024Mi"
            cpu: "2"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 3
      imagePullSecrets:
        - name: takima-school-registry
{{- end }}