{{- if .Values.pg.enabled }}
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: {{ include ("MyAppCtx.fullname") . }}-pg
spec:
  enableLogicalBackup: {{ .Values.pg.operator.enableLogicalBackup }}
  logicalBackupSchedule: 30 00 * * *
  teamId: {{ include ("MyAppCtx.fullname") . }}
  volume:
    size: {{ .Values.pg.operator.volumeSize }}
  numberOfInstances: {{ .Values.pg.operator.numberOfInstances }}
  users:
    cdb:
      - superuser
      - createdb
  databases:
    cdb: cdb  # dbname: owner
  postgresql:
    version: "14"
{{- end }}